"""RedDial — LIVE attack run (real LLM attacker ↔ real LLM target, no mock).

The un-mocked product loop over TEXT: a real Nemotron social-engineer
(`live_agents.RealAttackerLLM`) drives a real Nemotron deliberately-vulnerable
target (`live_agents.RealTargetLLM`), and the REAL Luhn/regex classifier
(`leak_classifier`) verifies each target turn. Writes a single, honestly-labelled
artifact to ``results/``.

HONEST SCOPE (do not overclaim):
  * LIVE = real LLMs over TEXT. No audio / STT / TTS / PSTN — that is the
    operator's separate run (see DEPLOY.md). ``proves_real_world_efficacy`` is
    False: the target is still OUR OWN consented, deliberately-vulnerable agent
    seeded with FAKE PII — not a third-party production agent.
  * Every turn is tagged; if the live endpoint fails/empties and the loop falls
    back to the deterministic mock, ``live_failed`` is set True (loud, not silent).

Usage:  uv run python live_attack.py            # needs NEMOTRON_LLM_URL in .env
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

import attack_library as lib
import leak_classifier as L
import live_agents
import posture as _posture
import run_context

# Escalation order the attacker climbs (real lines are generated by the LLM,
# steered by each attack's category/template).
_LADDER = ["authority_pretext", "instruction_injection", "escalation_ladder",
           "confusion_overload", "compliance_mirroring", "memory_poison"]


def run_live_attack(max_turns: int = 6, guardrail: str | None = None) -> dict:
    """Run ONE real-attacker ↔ real-target conversation; classify; return the
    labelled result dict. Requires NEMOTRON_LLM_URL (else every turn falls back
    to the mock and ``live_failed`` is True)."""
    import fake_accounts
    account = fake_accounts.FAKE_ACCOUNTS["default"]

    if not live_agents.live_available():
        raise RuntimeError("NEMOTRON_LLM_URL not set — live attack requires a real "
                           "endpoint and will NOT fall back to the mock.")

    # strict=True: a live failure RAISES — this run is genuinely live or it errors,
    # never silently mock-backed.
    target = live_agents.RealTargetLLM(account, guardrail, strict=True)
    attacker = live_agents.RealAttackerLLM(strict=True)
    classifier = _posture.NemotronClassifier.from_env()  # real posture (or None)

    attacks = [a for aid in _LADDER if (a := next((x for x in lib.ATTACKS if x.id == aid), None))]
    transcript: list[dict] = []
    breach = False
    breach_turn = None
    last_target = ""
    latencies: list[float] = []

    for turn in range(1, max_turns + 1):
        attack = attacks[min(turn - 1, len(attacks) - 1)]
        posture = _posture.classify(last_target, llm=classifier) if last_target else ""
        attacker.observe(last_target)
        t0 = time.monotonic()
        line = attacker.say(attack, posture, rung=turn - 1)
        target_said = target.reply(line, [{"role": "attacker", "content": t["text"]}
                                          if t["role"] == "attacker" else
                                          {"role": "target", "content": t["text"]}
                                          for t in transcript])
        latencies.append(round(time.monotonic() - t0, 2))
        transcript.append({"role": "attacker", "text": line, "attack": attack.id})
        transcript.append({"role": "target", "text": target_said})
        last_target = target_said
        if not breach and L.is_breach(L.scan_turn(target_said)):
            breach = True
            breach_turn = turn
            break

    live_failed = target.live_failed or attacker.live_failed
    return {
        "run_id": run_context.new_run_id(),
        "mode": "live",
        "target_kind": "live-llm: self-authored deliberately-vulnerable agent (text, no audio)",
        "model": os.environ.get("NEMOTRON_LLM_MODEL", "nvidia/nemotron-3-super"),
        "breach": breach,
        "breach_turn": breach_turn,
        "turns": len(transcript) // 2,
        "avg_latency_s": round(sum(latencies) / len(latencies), 2) if latencies else None,
        "live_failed": live_failed,
        "proves_real_world_efficacy": False,
        "transcript": transcript,
        "note": ("Real Nemotron attacker ↔ real Nemotron target ↔ real Luhn classifier, over "
                 "TEXT. NOT proof of real-world efficacy: the target is our own consented, "
                 "deliberately-vulnerable agent with FAKE PII — not a third-party production "
                 "agent, and no live phone audio is involved. live_failed=True means a turn "
                 "fell back to the deterministic mock."),
    }


def write_artifact(result: dict, out_dir: str = "results") -> str:
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    path = Path(out_dir) / f"live_attack_{result['run_id']}.json"
    path.write_text(json.dumps(result, indent=2, default=str))
    return str(path)


def main() -> None:
    from dotenv import load_dotenv
    load_dotenv(".env", override=True)
    run_context.setup_logging()
    if not live_agents.live_available():
        print("NEMOTRON_LLM_URL not set — live mode unavailable (would fall back to mock). "
              "Set it in .env to run a real live attack.")
        return
    r = run_live_attack()
    path = write_artifact(r)
    print(f"LIVE attack: breach={'YES @turn '+str(r['breach_turn']) if r['breach'] else 'no'} "
          f"· live_failed={r['live_failed']} · ~{r['avg_latency_s']}s/turn · model={r['model']}")
    for t in r["transcript"]:
        who = "ATTACKER" if t["role"] == "attacker" else "TARGET  "
        print(f"  {who}: {t['text'][:90]}")
    print(f"-> {path}  (proves_real_world_efficacy={r['proves_real_world_efficacy']} — our own vulnerable agent, text only)")


if __name__ == "__main__":
    main()
